name: GhosttlyTermLinkkY
options:
  bundleIdPrefix: com.ghosttly
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  
settings:
  base:
    SWIFT_VERSION: "5.10"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.1.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  GhosttlyTermLinkkY:
    type: application
    platform: iOS
    sources:
      - path: GhosttlyTermLinkkY/Sources
        excludes:
          - "**/Info.plist"
    resources:
      - path: GhosttlyTermLinkkY/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ghosttly.termlinky
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIUserInterfaceStyle: Dark
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSAppTransportSecurity_AllowsArbitraryLoads: YES
        INFOPLIST_KEY_CFBundleDisplayName: TermLinky
